Improve Windows GH Actions workflow

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -1,84 +1,39 @@
 name: windows
 
 on:
-  # push:
-  #   branches:
-  #     - '*'
-  #   tags-ignore:
-  #     - '*'
   workflow_dispatch:
   pull_request:
 
 jobs:
-  perl:
-    # name: Perl Perl ${{ matrix.perl }} on ${{ matrix.os }}
-    # https://justatheory.com/2021/11/cache-perl-github-workflows/
-    env:
-      # some plugins still needs this to run their tests...
-      PERL_USE_UNSAFE_INC: 0
-      AUTHOR_TESTING: 1
-      AUTOMATED_TESTING: 1
-      RELEASE_TESTING: 1
-
-    # strategy:
-    #   matrix:
-    #    os: [ windows ]
-    #    perl: [ 'latest' ]
+  test:
     runs-on: windows-latest
-    # runs-on: ${{ matrix.os }}-latest
-
     steps:
       - id: checkout
         name: Checkout
         uses: actions/checkout@v4
-      # # - id: 
-      #   name: Setup DotNet@v1
-      # #   uses: actions/setup-dotnet@v1
 
-    # strategy:
-    #   fail-fast: false
-    #   matrix:
-    #     perl-version:
-    #       - 'latest'
-    #       - '5.34'
-    #       - '5.28'
-    #       # - '5.16' No dzil
-    #       # - '5.10' No dzil
-    #
-    # container:
-    #   image: perldocker/perl-tester:${{ matrix.perl-version }}
+      - id: setup-strawberry-perl
+        name: Setup Strawberry Perl
+        uses: shogo82148/actions-setup-perl@v1
+        with:
+          perl-version: '5.42'
+          distribution: strawberry # Critical for Windows compatibility
 
-      # - id: cache-cpan
-      #   name: Cache CPAN modules
-      #   uses: actions/cache@v4
-      #   # env:
-      #   #   cache-name: cache-cpan-modules
-      #   with:
-      #     # npm cache files are stored in `~/.npm` on Linux/macOS
-      #     # path: ~/.cpan
-      #     # path: local
-      #     path: C:/Strawberry/perl/site/lib
-      #     # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-      #     # key: perl-${{ steps.perl.outputs.perl-hash }}
-      #     key: static
-      #     # restore-keys: |
-      #     #   ${{ runner.os }}-build-${{ env.cache-name }}-
-      #     #   ${{ runner.os }}-build-
-      #     #   ${{ runner.os }}-
-
-      # # - id: 
-      #   name: Checkout
-      # #   uses: actions/checkout@v1
       - id: explore-tools-perl
         name: Explore Tools Perl
+        shell: pwsh
         run: |
           perl -V
+
       - id: explore-tools-cpan
         name: Explore Tools Cpan
+        shell: pwsh
         run: |
           cpan -V
+
       - id: explore-filesystem
         name: Explore Filesystem
+        shell: pwsh
         run: |
           dir
           dir C:\
@@ -89,42 +44,88 @@ jobs:
           dir D:\
           # dir .cpan
           # dir .cpan\build
+
       - id: explore-whoami
         name: Explore Who Am I
+        shell: pwsh
         run: |
           whoami
+
       - id: explore-environment
         name: Explore Environment
+        shell: pwsh
         run: |
           Get-ChildItem env: | Format-Table -Wrap
-      - id: install-cpanm
-        name: Install cpanm
+
+      - id: install-test2
+        name: Install Test2
+        shell: pwsh
         run: |
-          cpan -T App::cpanminus
-      - id: install-special-cases-first
-        name: Install Special Modules Which Require Special Care
-        run: |
-          cpanm --verbose --notest Term::ReadLine::Perl5
-      - id: install-dzil
+          cpanm --notest --force Test2::Suite
+
+      - id: install-dist-zilla
         name: Install Dist::Zilla
+        shell: pwsh
         run: |
-          cpanm --verbose --notest Dist::Zilla
-      # # - id: 
-      #   name: Install Dependencies
-      # #   #run: cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
-      # #   run: cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
-      # # - id: 
-      #   name: Makefile.PL
-      # #   run: perl Makefile.PL
-      - id: install-dzil-authordeps
-        name: Install Dist::Zilla Author Dependencies
+          cpanm --notest --force Dist::Zilla
+
+      - id: explore-missing-dzil-authordeps
+        name: Explore Missing Dist::Zilla Author Dependencies
+        shell: pwsh
         run: |
-          dzil authordeps --missing --versions | cpanm --verbose --force --notest || true
-      - id: install-deps
-        name: Install Dependencies
+          dzil authordeps --missing --cpanm-versions
+
+      - id: install-missing-dzil-authordeps
+        name: Install Missing Dist::Zilla Author Dependencies
+        shell: pwsh
         run: |
-          dzil listdeps --missing --develop --requires --recommends --suggests --version | cpanm --verbose --force --notest || true
+          $authDeps = dzil authordeps --missing --cpanm-versions
+          if ($authDeps) {
+            Write-Host "Installing missing author dependencies: $authDeps"
+            $authDeps | cpanm --verbose --force --notest
+            if ($LASTEXITCODE -eq 1) {
+              Write-Host "cpanm returned 1, but checking if work got done..."
+              $authDepsCheck = dzil authordeps --missing
+            #   if ($authDepsCheck | ) {
+            #     Write-Host "Work got done successfully despite exit code 1."
+            #     $global:LASTEXITCODE = 0
+            #   }
+            }
+            $global:LASTEXITCODE = 0
+
+          } else {
+              Write-Host "No missing author dependencies found."
+          }
+
+      - id: explore-missing-deps
+        name: Explore Missing Dependencies
+        shell: pwsh
+        run: |
+          dzil listdeps --missing --develop --requires --no-recommends --no-suggests --cpanm-version
+
+      - id: install-missing-deps
+        name: Install Missing Dependencies
+        shell: pwsh
+        run: |
+          $listDeps = dzil listdeps --missing --develop --requires --no-recommends --no-suggests --cpanm-version
+          if ($listDeps) {
+            Write-Host "Installing missing dependencies: $listDeps"
+            $listDeps | cpanm --verbose --force --notest
+            if ($LASTEXITCODE -eq 1) {
+              Write-Host "cpanm returned 1, but checking if work got done..."
+              dzil listdeps --missing --develop --requires  --no-recommends --no-suggests
+            #   if ($?) {
+            #     Write-Host "Work got done successfully despite exit code 1."
+            #     $global:LASTEXITCODE = 0
+            #   }
+            }
+            $global:LASTEXITCODE = 0
+          } else {
+            Write-Host "No missing dependencies found."
+          }
+
       - id: run-tests
         name: Run Tests
+        shell: pwsh
         run: |
-          prove -lrv t
+          dzil test --no-author
